   version: '3.8'

   services:
     web:
       build: .
       container_name: vbot-web
       restart: always
       ports:
         - "5001:5001"
       volumes:
         - ./static:/app/static
         - ./uploads:/app/uploads
         - ./logs:/app/logs
       environment:
         - FLASK_APP=run.py
         - FLASK_ENV=production
         - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/vbot
         - SECRET_KEY=${SECRET_KEY}
         - APP_NAME=VBot
         - SERVER_NAME=vbot.autos
       depends_on:
         - db
       networks:
         - vbot-network
       command: >
         sh -c "flask db upgrade && 
                gunicorn --bind 0.0.0.0:5001 --workers 4 --timeout 120 'app:create_app(\"production\")'"

     db:
       image: postgres:14
       container_name: vbot-db
       restart: always
       environment:
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_USER=postgres
         - POSTGRES_DB=vbot
       volumes:
         - postgres_data:/var/lib/postgresql/data
       ports:
         - "5432:5432"
       networks:
         - vbot-network

   networks:
     vbot-network:
       driver: bridge

   volumes:
     postgres_data:
