version: '3.8'

services:
  web:
    build: .
    container_name: tracking-tool-web
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./static:/app/static
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/tracking_tool
      - SECRET_KEY=${SECRET_KEY}
      - APP_NAME=Tracking Tool
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USE_TLS=True
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - ADMINS=${ADMIN_EMAIL}
    depends_on:
      - db
    networks:
      - tracking-network
    command: gunicorn --bind 0.0.0.0:5001 --workers 4 --timeout 120 'app:create_app("docker")'

  db:
    image: postgres:14
    container_name: tracking-tool-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tracking_tool
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tracking-network

  nginx:
    image: nginx:latest
    container_name: tracking-tool-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/app/static
    depends_on:
      - web
    networks:
      - tracking-network

networks:
  tracking-network:
    driver: bridge

volumes:
  postgres_data: 